# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx1536m

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true
BUILD_TOOLS_VERSION=34
COMPILE_SDK_VERSION=34
android.useAndroidX=true
android.enableJetifier=true
camerax_version=1.4.0-alpha05
camerax_view_version=1.4.0-alpha05
camerax_ext_version=1.4.0-alpha05
camerax_lifecycle_version=1.4.0-alpha05
gson_version=2.10.1
app_compat_version=1.6.1



## Grouping
GROUP=io.github.triniwiz

## Metadata
POM_DESCRIPTION=Fancy Android Camera.
POM_DEVELOPER_EMAIL=fortune.osei@yahoo.com
POM_DEVELOPER_ID=triniwiz
POM_DEVELOPER_NAME=Osei Fortune
POM_SCM_CONNECTION=scm\:git@github.com\:triniwiz/fancycamera.git
POM_SCM_DEV_CONNECTION=scm\:git@github.com\:triniwiz/fancycamera.git
POM_SCM_URL=https\://github.com/triniwiz/fancycamera
POM_URL=https\://github.com/triniwiz/fancycamera
POM_INCEPTION_YEAR=2019

VERSION_MAJOR=4
VERSION_MINOR=0
VERSION_PATCH=0
VERSION_NAME=4.0.0-alpha.3
android.nonTransitiveRClass=false
android.nonFinalResIds=false